# Generated by Django 4.1.7 on 2023-04-29 12:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.CharField(max_length=50)),
                ('dr_email', models.CharField(max_length=50)),
                ('dr_addr', models.CharField(max_length=50)),
                ('dr_mobile', models.CharField(max_length=50)),
                ('dr_gender', models.CharField(max_length=50)),
                ('dr_age', models.CharField(max_length=50)),
                ('dr_exprience', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hopsital_department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
                ('discriptions', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Add_patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_email', models.CharField(max_length=50)),
                ('patient_phone', models.CharField(max_length=50)),
                ('patient_age', models.CharField(max_length=50)),
                ('patient_gender', models.CharField(max_length=50)),
                ('patient_blood', models.CharField(max_length=50)),
                ('patient_addr', models.CharField(max_length=50)),
                ('patient_start_dt', models.DateField(default=datetime.date(2023, 4, 29))),
                ('patient_end_dt', models.DateField(default=datetime.date(2023, 4, 29))),
                ('fk_dr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_admins.doctor')),
            ],
        ),
    ]
