# Generated by Django 4.1.7 on 2023-04-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_admins', '0002_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_patient',
            name='patient_end_dt',
            field=models.DateField(),
        ),
    ]
