# Generated by Django 4.1.7 on 2023-04-29 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_admins', '0003_alter_add_patient_patient_end_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('appointment_date', models.DateField()),
                ('problem', models.TextField()),
                ('fk_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_admins.departments')),
                ('fk_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_admins.doctor')),
            ],
        ),
    ]
