# Generated by Django 4.1.7 on 2023-04-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_admins', '0005_alter_add_patient_patient_start_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='dr_depart',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
