# Generated by Django 4.1.7 on 2023-04-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_admins', '0007_remove_add_patient_patient_end_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='available_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='per_patient_time',
            field=models.CharField(max_length=50),
        ),
    ]
