# Generated by Django 4.1.7 on 2023-04-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_admins', '0008_alter_schedule_available_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
