# Generated by Django 4.1.7 on 2023-04-30 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_admins', '0009_alter_schedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_patient',
            name='patient_update_dt',
            field=models.DateField(default=datetime.date(2023, 4, 30)),
        ),
    ]
